# Generated by Django 5.1.6 on 2026-03-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.DecimalField(decimal_places=0, max_digits=15)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
