# Generated by Django 5.1.6 on 2026-03-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='f_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='l_name',
            new_name='lname',
        ),
    ]
